### ISSUE TITLE
android app?

### ISSUE THREAD

**Issue by swedebugia** [evanrmurphy/note-recognition#7]
Hi. Would it be possible to create a simple android app from this?

**Comment by evanrmurphy** [comment]
Hi @swedebugia, thanks for writing in.

The code in this repo was out of date. I have rewritten this app with a new architecture so I could more easily introduce new features and so that it more seamlessly integrates with the product that it was built for, [SightReadingMastery](https://sightreadingmastery.com/).

The app itself still lives [here](http://sightreadingmastery.com/note-recognition). It's alive and well and works on Android in the web browser. I'm considering creating a native Android app for this, however we don't have one yet.
